### ISSUE TITLE
Feedback on improving usability...

### ISSUE THREAD

**Issue by miguelestrada** [watsonwork/watsonwork-authorize-as-user#1]
Great example with guidance UI for a complex topic !

Here some suggestions to make it even better:

1.  Indicate URL to paste for the callback in oauth (ie. https://localhost:3000/ )
2. Not sure if this is the reason why, but if after having entered invalid credentials in IBM ID then the following error keeps getting returned.  Only way out of it is to use a different browser or an incognito window... as the call to IBM ID authentication likely kept using stored cookie....

OAuth Error

error="invalid_client", error_description="Bad client credentials"

**Comment by ghost** [comment]
Updated README.md to include use of https://localhost:3000/ as a callback URI. Will create a separate issue for #2 for investigation.

**Comment by ghost** [comment]
PR for issue #2
